# Generated by Django 4.0.10 on 2023-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
