# Generated by Django 4.0.10 on 2023-05-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producs',
            new_name='Product',
        ),
    ]
